version: "3"
services:
  postgres_server_boilerplate:
    image: postgres
    container_name: postgres_server_boilerplate
    environment:
      POSTGRES_PASSWORD: ""
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin_server_boilerplate:
    image: dpage/pgadmin4
    container_name: pgadmin_server_boilerplate
    environment:
      PGADMIN_DEFAULT_EMAIL: "miguelangeltorresfp@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "16543:80"
    depends_on:
      - postgres_server_boilerplate

  redis_server_boilerplate:
    image: "redis:alpine"
    container_name: redis_server_boilerplate
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
